name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./hunkerdowns.club
    steps:
      - uses: actions/checkout@v4
      - name: Deploy the static website to gh-pages
        run: npm run deploy
