name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run:
        shell: bash
        working-directory: ./hunkerdowns.club
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: set git email
        run: git config --global user.email "shodan@hunkerdowns.club"
      - name: set git name
        run: git config --global user.name "Shodan"
      - name: install node modules
        run: npm install --no-audit
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "Sean Idzenga <sean.idzenga@protonmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
